// Ortak envanter — koda gömülüdür; kopyalayan/başka kullanıcı da aynı listeyi görür.
export const PUBLISHED_TOPICS = [
  "Boşanma Davasında Kusur Tespiti: Hangi Davranışlar Ağır Kusur Sayılır?",
  "İşveren Sigorta Primini Eksik Yatırırsa İşçi Ne Yapabilir?",
  "Boşanmada Ortak Konuttan Kim Ayrılmak Zorunda? Tedbir Kararı ve Evden Çıkarma Süreci",
  "İşveren İzinsiz Ücret Kesintisi Yapabilir mi? SGK, Vergi ve Hukuki Sonuçları",
  "Suça sürüklenen çocuk ceza alır mı? (11. Yargı Paketi)",
  "AYM süresiz nafaka kararı ve etkileri",
  "İşçi hakları ve kıdem tazminatı",
  "12. Yargı Paketi ve İBAN kiralama cezası",
  "2026 trafik cezaları ve itiraz yolları",
  "Yargıtay kararı: yıllık izne denk gelen hafta tatili düşülemez",
  "Trafik kazası sonrası araç değer kaybı ve tazminat",
  "Kiracı tahliye süreçleri",
  "Trafik çevirmesinde haksız ehliyet iptali",
  "Araç değer kaybı nasıl alınır",
  "Ortaklığın giderilmesi (izale-i şuyu) davaları",
  "İş kazası sonrası talep edilebilecek tazminatlar",
  "İşe iade davası ve işçi hakları",
  "Sahte e-ticaret sitesi dolandırıcılığı",
  "Kira tespit davası 2026",
  "Banka hesabı kiralama suçu",
  "WhatsApp mesajları mahkemede delil sayılır mı",
  "Kapora dolandırıcılığı ve sahte ilan",
  "Sosyal medya hakaret suçu ve şikayet süreci",
  "GSM taahhüt iptali cezası",
  "Boşanma davası açmadan önce bilinmesi gereken 5 kritik adım",
  "Velayet davalarında çocuğun görüşü ne zaman ve nasıl alınır?",
  "Mobbing (işyeri psikolojik taciz) nedir, işçi nasıl hak arar?",
];

export const IG_PUBLISHED_TOPICS = [
  "İşveren İzinsiz Ücret Kesintisi Yapabilir mi? SGK, Vergi ve Hukuki Sonuçları",
  "Boşanma Davasında Kusur Tespiti: Hangi Davranışlar Ağır Kusur Sayılır?",
  "İşveren Sigorta Primini Eksik Yatırırsa İşçi Ne Yapabilir?",
  "Boşanmada Ortak Konuttan Kim Ayrılmak Zorunda? Tedbir Kararı ve Evden Çıkarma Süreci",
  "12. Yargı Paketi / İBAN kiralama ceza indirimi düzenlemesi",
  "Maaş hesabına bankanın borç tahsili için blokaj koyması",
  "2026 güncel trafik cezaları ve itiraz süreçleri",
  "Yıllık izinde hafta tatili günlerinin düşülememesi",
  "Trafik çevirmesinde haksız ehliyet el koyma ve itiraz süresi",
  "Trafik kazası sonrası araç mahrumiyet bedeli",
  "İşten çıkarılan işçinin yasal hakları",
  "Ücretin düzensiz ödenmesi ve haklı fesih",
  "Taahhütlü sözleşmelerde erken fesih ve cezai şart",
  "CMK 134 / telefon incelemesinde rıza ile elde edilen delil",
  "Atatürk sözü / adalet-bağımsızlık alıntı paylaşımı",
  "Eşin evi terk etmesi ve boşanma süreci",
  "Senetlerde teminat iddiasının geçerliliği",
  "Vergi incelemesi nedir, vergi cezaları",
  "Özel güvenliğin adli arama yetkisi ve delil geçerliliği",
  "WhatsApp mesajlarının mahkemede delil değeri",
  "Ceza yargılamasında kesin ve inandırıcı delil / beraat ilkesi",
  "İhtiyaç sebebiyle tahliye (kendim oturacağım) davası",
  "Konut ihtiyacı nedeniyle kiracının tahliyesi",
  "Banka hesabına yatan paranın haczedilmesi",
  "Kredi kartıyla alınan ürünün gelmemesi / bedel iadesi",
  "Kurumsal: Av. Kürşat Demirelli ruhsat/tebrik gönderisi",
  "Reddi mirasa rağmen emekli maaşı/ikramiyenin mirasçılara ödenmesi",
  "Yeni infaz düzenlemesinden kimlerin yararlanamayacağı",
  "İstinaf sürecinde ikinci ek dilekçe verilebilmesi",
  "İstifa dilekçesi yazarken dikkat edilecekler",
  "İsteyen çalışır isteyen gider sözünün hukuki geçersizliği",
  "2025'te en çok artan suç: internet dolandırıcılığı",
  "Aile hukuku kararı (Yargıtay 2. HD)",
  "Atatürk anma / 10 Kasım alıntı paylaşımı",
  "KVK ihlali / rıza olmadan arama kayıtlarının kullanılması",
  "29 Ekim Cumhuriyet Bayramı kutlaması",
  "Ev sahipleri dikkat / kira konulu Yargıtay 12. HD kararı",
  "Ses kaydının delil olarak kullanılabilirliği",
  "Noter onayı olmayan kat malikleri kararının geçerliliği",
  "AYM'ye bireysel başvuru harç/şart değişikliği",
  "Geç ödenen borçta temerrüt faizi + enflasyon farkı",
  "Fahiş kira artışı hakkında en çok sorulan sorular",
  "Alkollü sürücü yerine aracı ben kullandım demenin suç olması",
  "30 Ağustos Zafer Bayramı kutlaması",
  "Emniyette avukatsız alınan ifadenin geçersizliği",
  "İşyerinde mobbing hakkında bilinmesi gerekenler",
  "Bankanın ödenen bedeli iade zorunluluğu",
  "Emekli maaşına haciz gelip gelmeyeceği",
  "Ceza hukuku kararı (Yargıtay 12. CD)",
  "2025 motosiklet trafik cezaları (kasksız sürüş)",
  "Yargıtay Hukuk Genel Kurulu kararı",
  "Hukukun üstünlüğü / adalet temalı paylaşım",
  "Delil amaçlı video çekmenin suç olup olmadığı",
  "Basit dolandırıcılık suçu nedir",
  "İstinafa başvurulmazsa temyiz hakkının durumu",
  "Kiracı olunan evin satılması ve yeni malikin tahliye hakkı",
  "Mirastan çıkarma / saklı pay",
  "İşe iade davası nedir",
  "Kendi isteğiyle ayrılan işçiye yıllık izin ücreti ödenmesi",
  "2025 İnfaz Yasası değişikliği kapsamlı bilgi",
  "Ortak alanlarda kamera kullanımı",
  "Kasten yaralama suçu nedir",
  "Ortak konutun mahremiyeti / eşler arası karar",
  "Kurumsal: Av. Beyza Nur Topal tanıtımı",
  "Ceza hukuku kararı (Yargıtay 8. CD)",
  "Evlilik dışı doğan çocuklarda velayet ve soyadı hakkı",
  "Kişisel verilerle ilgili Yargıtay 12. CD kararı",
  "Boşanmada mal paylaşımı hakkında bilinmesi gerekenler",
  "İdari gözetim nedir (sınır dışı edilecek yabancılar)",
  "Süresiz nafaka kalkıyor mu / aile hukuku değişikliği",
  "İhbar tazminatı nedir",
  "5 Nisan Avukatlar Günü kutlaması",
  "Kıdem tazminatı nedir",
  "Alkolmetre ölçümünde yapılan hata",
  "Adli arama hakkında bilinmesi gerekenler",
  "İşyerinde dedikodu ve iftiranın tazminatsız fesih sebebi olması",
  "10. Yargı Paketi neleri kapsıyor",
  "Estetik operasyon mağduriyetleri / hasta hakları (malpraktis)",
  "Önleme araması nedir",
  "Trafikte alkol sınırı ve cezaları",
  "Yoksulluk nafakası nedir",
  "Ocak ayı zam / güncel merak edilen konu (TÜİK)",
  "Kurumsal: Av. Ozan Sancar ruhsat/tebrik gönderisi",
  "Kiranın bankaya yatırılma zorunluluğu",
  "Atatürk / tarihî anma paylaşımı",
  "Sınır dışı etme (deport) kararı nedir",
  "10 Kasım Atatürk'ü anma",
  "Boşanma davası devam ederken ölüm hali ve miras hakkı",
  "Cinsiyet temelli şiddet konulu paylaşım",
  "Kurumsal: Av. Derya Betül Özer ruhsat/tebrik gönderisi",
  "Yalan yere yemin suçu",
  "Düğünde takılan takıların kime ait olduğu",
  "Kurumsal: staj tamamlama/tebrik gönderisi",
  "Trafik kazası kusur oranı hesaplaması",
  "Trafik kazasında manevi zararın karşılanması",
  "Arabuluculuk görüşmelerine katılmama halinde sonuçlar",
  "İcra ve İflas Kanunu'nda değişiklik",
  "Boşanmada zina sebebine dayanma şartları",
  "Fazla mesai alacağında faiz başlangıcı",
  "Aile içi şiddette hâkimin verebileceği koruyucu tedbirler",
  "Küçüğün yüksek yararı / velayet-koruma tedbiri",
  "6284 sayılı Kanun (aile içi şiddetin önlenmesi)",
  "Ev sahibinin banka hesabını kapatması durumunda kira ödeme",
  "Kira bedelinin ödenememesinin sonuçları",
  "İşçi ücretinin geç/düzensiz ödenmesi ve fesih hakkı",
  "Vekilin sorumluluğu (Yargıtay 13. HD)",
  "Malpraktis (doktor hatası) tanımı ve hekim sorumluluğu",
  "Kesin ve inandırıcı delil olmadan mahkumiyet verilememesi",
  "Atatürk Ey yükselen yeni nesil / Cumhuriyet paylaşımı",
  "AİHM kararı (2023)",
  "Ceza hukuku genel kurul kararı",
];

export const LI_KURUMSAL_TOPICS = [
  "İşveren İzinsiz Ücret Kesintisi Yapabilir mi? SGK, Vergi ve Hukuki Sonuçları",
  "Boşanma Davasında Kusur Tespiti: Hangi Davranışlar Ağır Kusur Sayılır?",
  "İşveren Sigorta Primini Eksik Yatırırsa İşçi Ne Yapabilir?",
  "Boşanmada Ortak Konuttan Kim Ayrılmak Zorunda? Tedbir Kararı ve Evden Çıkarma Süreci",
  "12. Yargı Paketi – İBAN kiralama cezaları (TCK 158)",
  "2026 güncel trafik cezaları – şirket filoları ve ticari risk",
  "Yıllık izinde hafta tatili günlerinin düşülememesi",
  "Sürücü belgelerinin haksız geri alınması – hak düşürücü süre",
  "Trafik kazalarında araç mahrumiyet zararı",
  "İşe iade – feshin son çare olması ilkesi",
  "MedDietCongress 2026 katılımı (etkinlik paylaşımı)",
  "Ücretin düzensiz ödenmesi – haklı fesih",
  "İş sağlığı ve güvenliği sunumu (etkinlik)",
  "CMK 134 – telefon incelemesi",
  "Vergi incelemesi ve hukuki süreç",
  "GPS/delil – somut delil olmadan mahkumiyet verilememesi",
  "Kredi kartıyla alınan ürünün teslim edilmemesi",
  "Adli sicil ve arşiv kaydı nasıl silinir (rehber)",
  "İstifa dilekçesine ne yazılmamalı",
  "Tahliye kararı ve kira sözleşmesinin yenilenmesi",
  "Mobbinge uğrayan işçi ve ihbar süresi",
];

export const LI_KISISEL_TOPICS = [
  "İşveren İzinsiz Ücret Kesintisi Yapabilir mi? SGK, Vergi ve Hukuki Sonuçları",
  "Boşanma Davasında Kusur Tespiti: Hangi Davranışlar Ağır Kusur Sayılır?",
  "İşveren Sigorta Primini Eksik Yatırırsa İşçi Ne Yapabilir?",
  "Boşanmada Ortak Konuttan Kim Ayrılmak Zorunda? Tedbir Kararı ve Evden Çıkarma Süreci",
  "İşverenin işçinin onayı olmadan ücretini düşürmesi",
  "12. Yargı Paketi – İBAN kiralama cezaları (TCK 158)",
  "2026 trafik cezaları – şirket filoları ve ticari risk",
  "Yıllık izinde hafta tatili sayılmaz",
  "Sürücü belgesi geri alma – hak düşürücü süre (15 gün)",
  "Araç mahrumiyet bedeli faturasız istenebilir",
  "Safranbolu Belediyesi / EuroTürk Derneği paylaşımı",
  "Senetlerde teminat iddiası her zaman geçerli değil",
  "Vergi incelemesi – ceza kesinleşti mi",
  "Ceza yargılamasında hukuka uygun delil ilkesi",
  "Dijital yazışmalar (WhatsApp) delil değeri",
  "Karabük Ceza Hukuku Avukatı iş ilanı (CMK)",
  "Mahkumiyet ancak kesin/somut delille (beraat)",
  "İhtiyaç sebebiyle tahliyede 3 yıl kuralı",
  "İhtiyaç nedeniyle tahliye (Yargıtay)",
  "Miras reddi her şeyi kapsamaz",
  "Adli sicil / arşiv kaydı silme rehberi",
  "İnfaz yasası – kapsam dışı suçlar",
  "İstinafta ikinci (ek) dilekçe verilebilir",
  "İstifa dilekçesine ne yazılmamalı",
  "İsteyen çalışır cümlesi fesih sayılır",
  "Sadakat yükümlülüğü boşanma sonrası da sürer",
];

// Bu araçla onaylanmış (2026-08-25 → 2026-09-20) 43 kayıt. platform: google | instagram | linkedin_kisisel | linkedin_kurumsal
const E = (topic, platform, type, branch, date) => ({ topic, platform, type, branch, date, content: "" });
const MIRAS_BORC = "Miras Bırakanın Borçları Mirasçılara Geçer mi? Mirası Kabul Etmeden Önce Dikkat Edilmesi Gerekenler";
const MIRAS_BORC_IG = "Miras Bırakanın Borçları Mirasçılara Geçer mi?MİRASI KABUL ETMEDEN ÖNCE BİLİNMESİ GEREKENLER";
const SUSPHELI = "Şüpheli Sıfatıyla İfade Vermeye Çağrıldığınızda Avukat Tutmadan Girilmemesi Gereken 5 Durum";
const SOSYAL = "Boşanma Davasında Sosyal Medya Paylaşımları Delil Olarak Kullanılabilir mi?";
const REKABET = "İş Sözleşmesinde Rekabet Yasağı Maddesi Geçerli midir? İşçi Hangi Koşullarda Bağlıdır?";
const MAL = "Boşanma Davası Açmadan Önce Mal Varlığı Tespiti: Eşin Mal Kaçırmasını Önlemenin Hukuki Yolları";
const DEPOZITO = "Kiracı Depozito İadesini Alamıyorsa Ne Yapabilir? İcra Yoluyla Geri Alma ve Dikkat Edilmesi Gereken Süreler";
const FAIZ = "Trafik Kazası veya İş Kazasında Tazminat Faizi Artık Ne Zaman Başlıyor? TBK m.55 Değişikliği";
const VELAYET = "Velayet Değişikliği Davası Ne Zaman Açılabilir? Koşullar ve Mahkemenin Aradığı Değişiklikler";
const UZLASMA = "Ceza Davasında Uzlaşma Nedir? Uzlaşmayı Kabul Etmeden Önce Bilinmesi Gereken 5 Risk";
const GORUS = "Çocukla Kişisel İlişki (Görüş) Kararına Uyulmaması: Şikayet Yolları ve Aile Mahkemesinin Yaptırımları";
const TUTUKLAMA = "Şüpheli veya Sanık Tutuklanabilmek İçin Hangi Koşullar Gerekir? Tutuklulukta Azami Süreler ve Tahliye Talebi";
const KAMERA = "İşyerinde Kamera Kaydı İşçinin Rızası Olmadan Delil Olarak Kullanılabilir mi? KVKK ve İş Hukuku Boyutuyla";
const TANIK = "Boşanma Davasında Tanık Beyanının Gücü ve Sınırları: Hangi Tanık İfadesi Mahkemeyi Bağlar?";

export const SEED_CUSTOM = [
  E(MIRAS_BORC, "google", "C", "MİRAS HUKUKU", "2026-08-25"),
  E(MIRAS_BORC_IG, "instagram", "Yargıtay Kartı", "MİRAS HUKUKU", "2026-08-25"),
  E(MIRAS_BORC_IG, "linkedin_kisisel", "Kişisel", "MİRAS HUKUKU", "2026-08-25"),
  E(MIRAS_BORC_IG, "linkedin_kurumsal", "Kurumsal", "MİRAS HUKUKU", "2026-08-25"),
  E("Anlaşmalı Boşanmada Protokol Şartları Sonradan Değiştirilebilir mi?", "instagram", "Carousel", "AİLE HUKUKU", "2026-08-28"),
  E(SUSPHELI, "google", "C", "CEZA HUKUKU", "2026-08-29"),
  E(SUSPHELI, "instagram", "Uzun Rehber", "CEZA HUKUKU", "2026-08-29"),
  E(SUSPHELI, "linkedin_kisisel", "Kişisel", "CEZA HUKUKU", "2026-09-02"),
  E(SOSYAL, "google", "C", "AİLE HUKUKU", "2026-09-02"),
  E(SOSYAL, "instagram", "Yargıtay Kartı", "AİLE HUKUKU", "2026-09-02"),
  E(SOSYAL, "linkedin_kisisel", "Kişisel", "AİLE HUKUKU", "2026-09-02"),
  E(REKABET, "google", "C", "İŞ HUKUKU", "2026-09-02"),
  E(REKABET, "instagram", "Kurumsal", "İŞ HUKUKU", "2026-09-02"),
  E(REKABET, "linkedin_kisisel", "Kişisel", "İŞ HUKUKU", "2026-09-02"),
  E(MAL, "instagram", "Yargıtay Kartı", "AİLE HUKUKU", "2026-09-08"),
  E(MAL, "linkedin_kisisel", "Kişisel", "AİLE HUKUKU", "2026-09-08"),
  E(MAL, "google", "C", "AİLE HUKUKU", "2026-09-08"),
  E(DEPOZITO, "google", "C", "KİRA HUKUKU", "2026-09-08"),
  E(DEPOZITO, "instagram", "Kurumsal", "KİRA HUKUKU", "2026-09-08"),
  E(DEPOZITO, "linkedin_kisisel", "Kişisel", "KİRA HUKUKU", "2026-09-08"),
  E(FAIZ, "google", "C", "TRAFİK & TAZMİNAT", "2026-09-08"),
  E(FAIZ, "instagram", "Kurumsal", "TRAFİK & TAZMİNAT", "2026-09-08"),
  E(FAIZ, "linkedin_kisisel", "Kişisel", "TRAFİK & TAZMİNAT", "2026-09-08"),
  E("HAGB Nedir, Yeni Düzenlemeyle Ne Değişti?", "google", "C", "CEZA HUKUKU", "2026-09-13"),
  E(VELAYET, "google", "C", "AİLE HUKUKU", "2026-09-13"),
  E(VELAYET, "instagram", "Yargıtay Kartı", "AİLE HUKUKU", "2026-09-13"),
  E(VELAYET, "linkedin_kisisel", "Kişisel", "AİLE HUKUKU", "2026-09-13"),
  E(UZLASMA, "google", "C", "CEZA HUKUKU", "2026-09-17"),
  E(UZLASMA, "instagram", "Carousel", "CEZA HUKUKU", "2026-09-17"),
  E(UZLASMA, "linkedin_kisisel", "Kişisel", "CEZA HUKUKU", "2026-09-17"),
  E(GORUS, "google", "C", "AİLE HUKUKU", "2026-09-19"),
  E(GORUS, "instagram", "Yargıtay Kartı", "AİLE HUKUKU", "2026-09-19"),
  E(GORUS, "linkedin_kisisel", "Kişisel", "AİLE HUKUKU", "2026-09-19"),
  E(TUTUKLAMA, "google", "C", "CEZA HUKUKU", "2026-09-20"),
  E(TUTUKLAMA, "instagram", "Yargıtay Kartı", "CEZA HUKUKU", "2026-09-20"),
  E(TUTUKLAMA, "linkedin_kisisel", "Kişisel", "CEZA HUKUKU", "2026-09-20"),
  E(KAMERA, "google", "C", "KVKK", "2026-09-20"),
  E(KAMERA, "instagram", "Reels", "İŞ HUKUKU", "2026-09-20"),
  E(KAMERA, "linkedin_kisisel", "Kişisel", "İŞ HUKUKU", "2026-09-20"),
  E(TANIK, "google", "C", "AİLE HUKUKU", "2026-09-20"),
  E(TANIK, "instagram", "Yargıtay Kartı", "AİLE HUKUKU", "2026-09-20"),
  E(TANIK, "linkedin_kisisel", "Kişisel", "AİLE HUKUKU", "2026-09-20"),
  E("Miras Kalan Taşınmazda Mirasçılar Anlaşamazsa Ne Olur? Satışa Zorlama ve Paylaşım Davası Süreci", "google", "C", "MİRAS HUKUKU", "2026-09-20"),
];
